export const POST_LOADING = "POST_LOADING";
export const SET_POSTS = "SET_POSTS";
export const SET_POSTS_ERROR = "SET_POSTS_ERROR";

export const ADD_POST_LOADING = "ADD_POST_LOADING";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_ERROR = "ADD_POST_ERROR";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_LOADING = "DELETE_POST_LOADING";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";

export const EDIT_POST_LOADING = "EDIT_POST_LOADING";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const POST_ACTIVITY_LOADING = "POST_ACTIVITY_LOADING";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_UNLIKE_SUCCESS = "POST_UNLIKE_SUCCESS";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_ACTIVITY_ERROR = "POST_ACTIVITY_ERROR";
export const SET_ALL_COMMENTS = "SET_ALL_COMMENTS";
export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const CLEAR_ERROR = "CLEAR_ERROR";
